import pytest
from selenium import webdriver
import sys
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
from time import sleep


@pytest.mark.lambdatest1_1
def test_lambdatest1_1():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("partial link text", "Home").click()
    driver.find_element("id", "enquiry_name").send_keys("Hari")
    time.sleep(5)
    driver.find_element("id", "enquiry_org_name").send_keys("gway")
    time.sleep(5)
    driver.find_element("id", "enquiry_phone").send_keys("6383902847")
    time.sleep(5)
    driver.find_element("id", "enquiry_email").send_keys("harilakshmi@gwayit.com")
    time.sleep(5)
    driver.find_element("xpath","//div[@class='row']/div//button[normalize-space()='Submit']").click()
    time.sleep(5)
    driver.close()


@pytest.mark.lambdatest1_2
def test_lambdatest1_2():
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text", "About").click()
        time.sleep(5)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(5)
        driver.close()

@pytest.mark.lambdatest1_3
def test_lambdatest1_3():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[@class='homeProLink']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[@class='homeProLink']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[@class='homeProLink']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[@class='homeProLink']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4400)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/crm.png']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4400)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/hrm.png']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4400)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/bi.png']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4400)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/purchase.png']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4800)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/workflow.jpg']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 4800)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/project.jpg']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 5000)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/vendor.jpg']").click()
    time.sleep(5)
    driver.find_element("link text", "Products").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 5000)")
    time.sleep(5)
    driver.find_element("xpath", "//img[@src='/assets/other_integrations.jpg']").click()
    time.sleep(5)
    driver.close()

@pytest.mark.lambdatest1_4
def test_lambdatest1_4():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("partial link text", "Servic").click()
    time.sleep(5)
    sliders = driver.find_elements("class name", "go_DOp")
    print(len(sliders))
    driver.find_element("xpath", "(//a[normalize-space()='Associated Development Center - ADC'])[1]").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(5)
    driver.close()

@pytest.mark.lambdatest1_5
def test_lambdatest1_5():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("partial link text", "Custome").click()
    time.sleep(5)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(5)
    driver.close()

@pytest.mark.lambdatest1_6
def test_lambdatest1_6():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("xpath", "(//a[normalize-space()='Contact Us'])[1]").click()
    time.sleep(5)
    driver.find_element("id", "enquiry_name").send_keys("Hari")
    time.sleep(5)
    driver.find_element("id", "enquiry_org_name").send_keys("Gway")
    time.sleep(5)
    driver.find_element("id", "enquiry_phone").send_keys("8925372968")
    time.sleep(5)
    driver.find_element("id", "enquiry_email").send_keys("harilakshmi@gwayit.com")
    time.sleep(5)
    driver.find_element("id", "enquiry_comments").send_keys("pass/fail")
    time.sleep(5)
    driver.execute_script("window.scrollTo(0, 600)")
    driver.find_element("xpath", "//button[@type='submit'][@data-callback='lead1RecaptchaForm']").click()
    time.sleep(5)
    driver.close()

@pytest.mark.lambdatest1_7
def test_lambdatest1_7():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("xpath", "//a[normalize-space()='Blogs']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Home']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Blogs']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='About Us']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Blogs']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Service']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Blogs']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Customers']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Blogs']").click()
    time.sleep(5)
    driver.find_element("xpath", "//a[normalize-space()='Contact Us']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("GwayERP As Software Development Center")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Why Business Intelligence Is A Key For Business")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("A Guide To Cloud ERP And How It Can Help Your Business")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Raising the bar with the right ERP!")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("ERP Solutions, the non-stop battery for your business!")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Design your business to define success!")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Mapping your business into success!")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(5)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(5)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(5)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("ERP and Cost Cutting")
    time.sleep(5)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Get your ROI Guaranteed!")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Agile Advantage For Your ERP With GWAY")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "//a[@class='mt-search-icon']").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Top 5 Ways For ERP In Financial Services")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("How to solve issues with ERP software?")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Why GwayERP ahead in Market?")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Inventory Management Module")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("GwayERP Best ERP software for Manufacturing Industry")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("ERP in the Textile Industry")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("ERP in Pharma industry")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Advantages Of SaaS in ERP")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Agile Methodology Overview")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Billing software")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Finance and Accounting")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Customer Relationship Management – CRM")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("HRMS")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Quality Assurance")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("How ERP works in the electrical industry")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Why Production Management System Is Essential?")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("SCHOOL MANAGEMENT SYSTEM")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("WHY BUSINESS INTELLIGENCE IS A KEY FOR BUSINESS")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.get("https://gwayerp.com/blog/")
    time.sleep(2)
    driver.find_element("xpath", "(//a[@class='mt-search-icon'])[1]").click()
    time.sleep(2)
    driver.find_element("xpath", "//input[@placeholder='Search …']").clear()
    driver.find_element("xpath", "//input[@placeholder='Search …']").send_keys("Supply Chain Management")
    time.sleep(2)
    driver.find_element("xpath", "//input[@value='Search']").click()
    time.sleep(2)
    driver.close()

@pytest.mark.lambdatest1_8
def test_lambdatest1_8():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("partial link text", "Caree").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0, 600)")
    time.sleep(2)
    driver.close()

@pytest.mark.lambdatest1_9
def test_lambdatest1_9():
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("link text", "Partners").click()
        time.sleep(2)
        driver.find_element("id", "partnership_name_1").send_keys("Hari")
        time.sleep(2)
        driver.find_element("id", "partnership_phone_1").send_keys("8925372968")
        time.sleep(2)
        driver.find_element("id", "partnership_org_name_1").send_keys("Gway")
        time.sleep(2)
        driver.find_element("id", "partnership_email_1").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("id", "partnership_comments").send_keys("good")
        time.sleep(2)
        driver.find_element("xpath", "(//button[@type='submit'][normalize-space()='Submit'])[3]").click()
        time.sleep(2)
        driver.close()

@pytest.mark.lambdatest1_10
def test_lambdatest1_10():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("link text", "Free Consultation").click()
    time.sleep(2)
    driver.find_element("xpath", "(//input[@id='lead_name_1'])[1]").send_keys("Hari")
    time.sleep(2)
    driver.find_element("xpath", "(//input[@id='lead_org_name_1'])[1]").send_keys("gway")
    time.sleep(2)
    driver.find_element("xpath", "(//input[@id='lead_phone_1'])[1]").send_keys("6383902847")
    time.sleep(2)
    driver.find_element("xpath", "(//input[@id='lead_email_1'])[1]").send_keys("harilakshmi@gwayit.com")
    time.sleep(2)
    driver.find_element("xpath", "(//button[@type='submit'][normalize-space()='Submit'])[2]").click()
    time.sleep(2)
    driver.close()


@pytest.mark.lambdatest1_11
def test_lambdatest1_11():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.find_element("partial link text", "Home").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//a[normalize-space()='Inventory Management']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//a[normalize-space()='Sales and Marketing']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//a[normalize-space()='Purchase']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Finance & Accounting'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Workflow Management'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Project Management'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='HR-Payroll'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='SCM'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='CRM'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Business Intelligence'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Vendor Management'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Other Integrations'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Career'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='ERP Software In Chennai'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    # driver.find_element("xpath", "(//a[normalize-space()='Manufacturing ERP Software'])[1]").click()
    # time.sleep(2)
    # driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    # time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Associated Development Center'])[1]").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "(//a[normalize-space()='Privacy Policy'])[1]").click()
    time.sleep(2)
    driver.close()


@pytest.mark.lambdatest1_12
def test_lambdatest1_12():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/")
    driver.maximize_window()
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//i[@class='ri-twitter-fill']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//i[@class='ri-facebook-fill']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//i[@class='ri-linkedin-fill']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//i[@class='ri-instagram-fill']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//a[@href='https://www.tumblr.com/gwayerp/']").click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
    time.sleep(2)
    driver.find_element("xpath", "//i[@class='ri-pinterest-fill']").click()
    time.sleep(2)
    driver.close()

@pytest.mark.lambdatest1_13
def test_lambdatest1_13():
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    driver.get("https://gwayerp.com/contact-us")
    driver.maximize_window()
    a=driver.find_element("partial link text", "info@gwayerp.c")
    print((a))
    time.sleep(2)
    driver.refresh()
    driver.close()




