from selenium import webdriver
import time
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.common.by import By

class enquiry():
    def home(self):
        driver=webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","Home").click()
        driver.find_element("id","enquiry_name").send_keys("Hari")
        time.sleep(2)
        driver.find_element("id","enquiry_org_name").send_keys("gway")
        time.sleep(2)
        driver.find_element("id","enquiry_phone").send_keys("6383902847")
        time.sleep(2)
        driver.find_element("id","enquiry_email").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("xpath","//div[@class='row']/div//button[normalize-space()='Submit']").click()
        time.sleep(2)
findbyid =enquiry()
findbyid.home()

class aboutus():
    def about(self):
        driver=webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","About").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
findbyid =aboutus()
findbyid.about()


class product():
    def products(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.find_element("xpath","(//a[@class='homeProLink'])[1]").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.find_element("xpath","(//a[@class='homeProLink'])[2]").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.find_element("xpath","(//a[@class='homeProLink'])[3]").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.find_element("xpath","(//a[@class='homeProLink'])[4]").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4400)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/crm.png']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4400)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/hrm.png']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4400)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/bi.png']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4400)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/purchase.png']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4800)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/workflow.jpg']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 4800)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/project.jpg']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 5000)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/vendor.jpg']").click()
        time.sleep(2)
        driver.find_element("link text", "Products").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 5000)")
        time.sleep(2)
        driver.find_element("xpath", "//img[@src='/assets/other_integrations.jpg']").click()
        time.sleep(2)
findbyid =product()
findbyid.products()


class service():
    def services(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","Servic").click()
        time.sleep(2)
        sliders=driver.find_elements("class name","go_DOp")
        print(len(sliders))
        driver.find_element("xpath","(//a[normalize-space()='Associated Development Center - ADC'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        # driver.find_element("xpath","(//a[normalize-space()='One Time Purchase - OTP'])[1]").click()
        # time.sleep(2)
        #driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        #time.sleep(2)
findbyid =service()
findbyid.services()


class customers():
    def customer(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","Custome").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
findbyid =customers()
findbyid.customer()


class contactus():
    def connectus(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("xpath","(//a[normalize-space()='Contact Us'])[1]").click()
        time.sleep(2)
        driver.find_element("id","enquiry_name").send_keys("Hari")
        time.sleep(2)
        driver.find_element("id","enquiry_org_name").send_keys("Gway")
        time.sleep(2)
        driver.find_element("id","enquiry_phone").send_keys("8925372968")
        time.sleep(2)
        driver.find_element("id","enquiry_email").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("id","enquiry_comments").send_keys("pass/fail")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 600)")
        driver.find_element("xpath","//button[@type='submit'][@data-callback='lead1RecaptchaForm']").click()
        time.sleep(5)
findbyid =contactus()
findbyid.connectus()

class blog():
    def blogs(self):
          driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
          driver.get("https://gwayerp.com/")
          driver.maximize_window()
          driver.find_element("xpath","(//a[normalize-space()='Blogs'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","//a[normalize-space()='Home']").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='Blogs'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='About'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='Blogs'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='Products'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='Blogs'])[1]").click()
          time.sleep(2)
          driver.find_element("xpath","(//a[normalize-space()='Customers'])[1]").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Benefits of ERP solutions")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Raising the bar with the right ERP!")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("ERP Solutions, the non-stop battery for your business!")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Design your business to define success!")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Mapping your business into success!")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("ERP and Cost Cutting")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Get your ROI Guaranteed!")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Agile Advantage For Your ERP With GWAY")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Top 5 ways how ERP applications help financial services firms drive sustainable growth?")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("How to solve issues with ERP software?")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Why GwayERP ahead in Market?")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Inventory Management Module")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("GwayERP Best ERP software for Manufacturing Industry")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("ERP in the Textile Industry")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("ERP in Pharma industry")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Advantages Of SaaS in ERP")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Agile Methodology Overview")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Billing software")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Finance and Accounting")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Customer Relationship Management – CRM")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("HRMS")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("Quality Assurance")
          time.sleep(2)
          driver.find_element("css selector","button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id", "wp-block-search__input-1").send_keys("How ERP works in the electrical industry")
          time.sleep(2)
          driver.find_element("css selector","button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id", "wp-block-search__input-1").send_keys("Why Production Management System Is Essential?")
          time.sleep(2)
          driver.find_element("css selector","button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id", "wp-block-search__input-1").send_keys("SCHOOL MANAGEMENT SYSTEM")
          time.sleep(2)
          driver.find_element("css selector", "button[type='submit']").click()
          time.sleep(2)
          driver.get("https://gwayerp.com/blog/")
          driver.find_element("id","wp-block-search__input-1").send_keys("WHY BUSINESS INTELLIGENCE IS A KEY FOR BUSINESS")
          time.sleep(2)
          driver.find_element("css selector","button[type='submit']").click()
          time.sleep(2)
findbyid =blog()
findbyid.blogs()

class career():
    def careers(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","Caree").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 600)")
        time.sleep(2)
        driver.find_element("xpath","(//button[normalize-space()='Click Here'])[1]").click()
        time.sleep(2)
        driver.find_element("xpath","(//input[@id='lead_name_1'])[1]").send_keys("Hari")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_org_name_1'])[1]").send_keys("gway")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_phone_1'])[1]").send_keys("8925372968")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_email_1'])[1]").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("xpath", "//button[@type='submit'][normalize-space()='Submit']").click()
        time.sleep(2)
findbyid =career()
findbyid.careers()

class partner():
    def partners(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("link text", "Partners").click()
        time.sleep(2)
        driver.find_element("id", "partnership_name_1").send_keys("Hari")
        time.sleep(2)
        driver.find_element("id", "partnership_phone_1").send_keys("8925372968")
        time.sleep(2)
        driver.find_element("id", "partnership_org_name_1").send_keys("Gway")
        time.sleep(2)
        driver.find_element("id", "partnership_email_1").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("id", "partnership_comments").send_keys("good")
        time.sleep(2)
        driver.find_element("xpath", "(//button[@type='submit'][normalize-space()='Submit'])[3]").click()
        time.sleep(2)
findbyid =partner()
findbyid.partners()

class demo():
    def demos(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("xpath", "(//a[normalize-space()='Schedule Your Demo'])[1]").click()
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_name_1'])[1]").send_keys("Hari")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_org_name_1'])[1]").send_keys("gway")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_phone_1'])[1]").send_keys("6383902847")
        time.sleep(2)
        driver.find_element("xpath", "(//input[@id='lead_email_1'])[1]").send_keys("harilakshmi@gwayit.com")
        time.sleep(2)
        driver.find_element("xpath", "(//button[@type='submit'][normalize-space()='Submit'])[2]").click()
        time.sleep(2)
findbyid = demo()
findbyid.demos()

class ourproducts():
    def products(self):
        driver=webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.find_element("partial link text","Home").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath","//a[normalize-space()='Inventory Management']").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath","(//a[normalize-space()='Sales and Marketing'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Purchase'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Finance & Accounting'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Workflow Management'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Project Management'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='HR-Payroll'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='SCM'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='CRM'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Business Intelligence'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Vendor Management'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Other Integrations'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//li)[29]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Career'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='ERP Software In Chennai'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Manufacturing ERP Software'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Associated Development Center'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[normalize-space()='Privacy Policy'])[1]").click()
        time.sleep(2)

class link():
    def links(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/")
        driver.maximize_window()
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath","(//i[@class='ri-twitter-fill'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//i[@class='ri-facebook-fill'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//i[@class='ri-linkedin-fill'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//i[@class='ri-instagram-fill'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//a[@href='https://www.tumblr.com/gwayerp/'])[1]").click()
        time.sleep(2)
        driver.execute_script("window.scrollTo(0,document.body.scrollHeight);")
        time.sleep(2)
        driver.find_element("xpath", "(//i[@class='ri-pinterest-fill'])[1]").click()
        time.sleep(2)
findbyid =link()
findbyid.links()

class address():
    def addresses(self):
        driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        driver.get("https://gwayerp.com/contact-us")
        driver.maximize_window()
        driver.find_element("partial link text","info@gwayerp.c").click()
        time.sleep(2)
        # a = driver.find_element("xpath", "(//a[contains(@target,'_blank')][normalize-space()='9176190007'])[3]").text
        # print((a))
        driver.quit()
findbyid =address()
findbyid.addresses()





